apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configapp

data:
  # Configuration values can be set as key-value properties
  # This created 1 file for each entry below at mounted location
  # e.g 1 file for 'database' key with filename database and 'mongodb' value inside, 
  database: mongodb
  database_uri: mongodb://localhost:27017
  environment: Dev
  MONGO_INITDB_ROOT_USERNAME: admin1

  
  # Or set as complete file contents (even JSON!). This creates 1 file at mounted location
  # with all key value pairs in it
  keys: | 
    image.public.key=771 
    rsa.public.key=42
