apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc    #refer pvc created from pvc.yml    
      containers:
      - name: mongodb
        image: mongo:latest
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/mongodb   #Path on container to mount        

        ports:
        - containerPort: 27017
        # Mongo user settings
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: adminuser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: Password1234!
        - name: MONGO_INITDB_DATABASE
          value: mydatabase